 name: StackIt
 version: 2.10
 description: A powerful API for Minecraft 1.7-1.11
 
 author: StackIt
 website: https://docs.uphoria.org/stackit/
 
 main: org.stackit.StackIt
 database: true
 
 commands:
     stackit:
         description: StackIt main command.
         usage: /stackit <option>
         aliases: [st]