 name: StackIt
 version: 3.0-alpha
 description: A powerful API for Minecraft 1.7-1.12.2
 
 author: Marethyun
 
 main: org.stackit.StackIt
 database: true
 
 commands:
     stackit:
         description: StackIt main command.
         usage: /stackit <option>
         aliases: [st]